# Generated by Django 2.0.4 on 2018-04-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FareWay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinates',
            name='X',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='Y',
            field=models.FloatField(),
        ),
    ]
