# Generated by Django 2.0.4 on 2018-04-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FareWay', '0002_auto_20180420_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinates',
            name='X',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='Y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
