# Generated by Django 2.0.5 on 2018-05-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FareWay', '0005_auto_20180420_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='coordinates',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Coordinates',
        ),
    ]
