# Generated by Django 2.0.5 on 2018-05-17 20:49

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('FareWay', '0005_auto_20180420_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='coordinates',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42),
        ),
        migrations.DeleteModel(
            name='Coordinates',
        ),
    ]
