# Generated by Django 2.0.3 on 2018-06-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FareWay', '0009_attraction_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='post_img'),
        ),
    ]
