# Generated by Django 2.0.3 on 2018-06-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FareWay', '0010_auto_20180605_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_img'),
        ),
    ]
