# Generated by Django 2.0.5 on 2018-06-07 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FareWay', '0011_auto_20180605_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripattraction',
            name='attraction',
        ),
        migrations.RemoveField(
            model_name='tripattraction',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='attractions',
        ),
        migrations.AddField(
            model_name='trip',
            name='attraction',
            field=models.ManyToManyField(related_name='attraction', to='FareWay.Attraction'),
        ),
        migrations.AddField(
            model_name='trip',
            name='end',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end', to='FareWay.Attraction'),
        ),
        migrations.AddField(
            model_name='trip',
            name='start',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start', to='FareWay.Attraction'),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_name',
            field=models.CharField(default='NazwaTrasy', max_length=50),
        ),
        migrations.DeleteModel(
            name='TripAttraction',
        ),
    ]
